name: babysitter
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ">=2.17.0-11.0.dev <3.0.0"



dependencies:
  flutter:
    sdk: flutter


  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  shared_preferences: ^2.0.12
  provider: ^6.0.2
  http: ^0.13.4
  flutter_svg: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0


flutter:


  uses-material-design: true

  assets:
    - assets/image/
    - assets/image/person.jpg
    - assets/icons/
  fonts:
     - family: Iransans
       fonts:
         - asset: assets/fonts/IRANSansWeb.ttf
         - asset: assets/fonts/BElham.ttf
           weight: 700